@startuml

'UML GENERE PAR CODE :)

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

class FieldUML{
-field: Field
-mod: int
+<<create>>FieldUML()
-name()
-type()
+lectureField(fVal: Field )

}
@enduml
