@startuml

'UML GENER PAR CODE :)

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

interface ClassUML{
-{static}cName: Class
-{static}uml: String
+classGet(c: Class ): String


}
'fin du code generé automatiquement
@enduml