@startuml
'https://plantuml.com/class-diagram

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

package java.lang
{
    class Class
    {
        toString() : String
        getDeclaredConstructors() : Constructor[*]
        forName(String className) : static Class<?>
        getCanonicalName() : String
        getDeclaredField() : Field
        getName() : String
        '   contien le package en plus
    }

    class Object
    {
        toString() : String
        getDeclaredClass() : Class
    }

    class String
    {
        compareTo() : Integer
        contains() : boolean
        endWith() : boolean
        length() : Integer
        split() : String[]
        toString() : String
    }
}

/'abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}'/

@enduml