@startuml

'UML GENER PAR CODE :)

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

class semaineTrois{
+{static}stringClass
+{static}cName
+{static}fichier
+{static}main() : String[] 
+{static}type() : Method 
+{static}classGet() : 
+{static}umlClass() : 
+{static}umlAtribute() : 
+{static}umlMethode() : 
+{static}ecriture() : 
-{static}visibilité() : Integer 

}
@enduml