@startuml

'UML GENER PAR CODE :)

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members



class ClassUML{
-{static}cName: Class
-{static}uml: String
+classGet(: Class )


}
@enduml

class ClassUML{
-{static}cName: Class
-{static}uml: String
+classGet(: Class )


}
@endumlclass Init{
+{static}stringClass: String
+{static}fichier: String
+{static}fichiers: String[]
+{static}debutEcriture()

+{static}ecriturePUML()

+{static}ecritureSVG()


}
@enduml

class ClassUML{
-{static}cName: Class
-{static}uml: String
+classGet(: Class )


}
@endumlclass Init{
+{static}stringClass: String
+{static}fichier: String
+{static}fichiers: String[]
+{static}debutEcriture()

+{static}ecriturePUML()

+{static}ecritureSVG()


}
@endumlclass FieldUML{
-{static}fVal: Field
-name()

-type()

+traitementField(: Field )

-visibilite(: Integer )


}
@enduml